using Entidades.DTO;
using Pangea.Entidades.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pangea.Entidades.DTO
{
    public class AnagraficaDTO
    {
        //public string SQLTypeName { get; set; }
        public string advlecturista { get; set; }
        public string cap { get; set; }
        public string capEsaz { get; set; }
        public string cdClMerceologica { get; set; }
        public string cft { get; set; }
        public string cifreAtt { get; set; }
        public string cifreDecimaliAttiva { get; set; }
        public string cifreDecimaliPotenza { get; set; }
        public string cifreDecimaliReattiva { get; set; }
        public string cifrePotenza { get; set; }
        public string cifreReattiva { get; set; }
        public string classe { get; set; }
        public string classeESub { get; set; }
        public string clienteSpeciale { get; set; }
        public string codContributo { get; set; }
        public string codEsazione { get; set; }
        public string codInserzionePotenza { get; set; }
        public string codMisuratorePot { get; set; }
        public string codMisuratoreRea { get; set; }
        public string codU { get; set; }
        public string codiceFiscale { get; set; }
        public string codiceGruppo { get; set; }
        public string codiceMis { get; set; }
        public string codicePresa { get; set; }
        public string codiceZona { get; set; }
        public string codigoNroConfig { get; set; }
        public string codigoPartido { get; set; }
        public string cognome { get; set; }
        public string componenteAuc { get; set; }
        public string comuneEsaz { get; set; }
        public string constEnrgAttivaFrF3 { get; set; }
        public string constEnrgAttivaHpF2 { get; set; }
        public string constEnrgAttivaHrF1 { get; set; }
        public string constEnrgDncrHpReattivaF2 { get; set; }
        public string constEnrgDncrReattivaFpF4 { get; set; }
        public string constEnrgDncrReattivaHrF6 { get; set; }
        public string constEnrgPtnzAttivaFpF3 { get; set; }
        public string constEnrgPtnzAttivaHpF2 { get; set; }
        public string constEnrgPtnzAttivaHrF1 { get; set; }
        public string constEnrgUferFpReattivaF3 { get; set; }
        public string constEnrgUferHpReattivaF1 { get; set; }
        public string constEnrgUferReattivaHrF5 { get; set; }
        public string costE { get; set; }
        public string costP { get; set; }
        public string dataCessazione { get; set; }
        public string dataDecorrenzaMis { get; set; }
        public string dataEfficacia { get; set; }
        public string dataFatturazioneFissa { get; set; }
        public string dataFineProva { get; set; }
        public string dataInizioProva { get; set; }
        public string dataScadenzaStr { get; set; }
        public string determinazContiContratti { get; set; }
        public string dtAllacciamento { get; set; }
        public string dtContratto { get; set; }
        public string dtFirmaContrCommittStr { get; set; }
        public string dtFirmaContrContraeStr { get; set; }
        public string eneltel { get; set; }
        public string eneltelPrecedente { get; set; }
        public string enerAnnuaCott { get; set; }
        public string energiaAdF3Ael { get; set; }
        public string energiaAdF3Ass { get; set; }
        public string flagMandatoConnessione { get; set; }
        public string flagMisPot { get; set; }
        public string flagMisuratoreInterno { get; set; }
        public string flagSwitchCessato { get; set; }
        public string flagTG { get; set; }
        public string fondoScala { get; set; }
        public string frequenzaLettura { get; set; }
        public string gestoreRete { get; set; }
        public string idDispacc { get; set; }
        public string idFase { get; set; }
        public string idTipoFornit { get; set; }
        public string inicial { get; set; }
        public string interno { get; set; }
        public string interseccion { get; set; }
        public string latitudine { get; set; }
        public string letturaAttF1 { get; set; }
        public string letturaAttF2 { get; set; }
        public string letturaAttF3 { get; set; }
        public string letturaAttF4 { get; set; }
        public string letturaPotF1 { get; set; }
        public string letturaPotF2 { get; set; }
        public string letturaPotF3 { get; set; }
        public string letturaPotF4 { get; set; }
        public string letturaReaF1 { get; set; }
        public string letturaReaF2 { get; set; }
        public string letturaReaF3 { get; set; }
        public string letturaReaF4 { get; set; }
        public string localita { get; set; }
        public string longitudine { get; set; }
        public string matr1ta { get; set; }
        public string matr2ta { get; set; }
        public string matr3ta { get; set; }
        public string matr4ta { get; set; }
        public string matrMisuratorePot { get; set; }
        public string matrMisuratoreRea { get; set; }
        public string matricolaMis { get; set; }
        public string nazioneEsaz { get; set; }
        public string nome { get; set; }
        public string nominativo { get; set; }
        public string nonDisalimentabile { get; set; }
        public string noteAccesso { get; set; }
        public string numCiv { get; set; }
        public string numTel1 { get; set; }
        public string oreUtilizzo { get; set; }
        public string partitaIVA { get; set; }
        public string percMaggiorazione { get; set; }
        public string piano { get; set; }
        public string pod { get; set; }
        public string potAggDetrazF3 { get; set; }
        public string potAggDetrazF3_2 { get; set; }
        public string potContrCottimo { get; set; }
        public string potDisp { get; set; }
        public string potImpegnata { get; set; }
        public string potProduzione { get; set; }
        public string potenzaFranchigia { get; set; }
        public string precintoT1 { get; set; }
        public string precintoT2T3N1 { get; set; }
        public string precintoT2T3N2 { get; set; }
        public string precintoT2T3N3 { get; set; }
        public string precintoT2T3N4 { get; set; }
        public string prefisso { get; set; }
        public string provincia { get; set; }
        public string provinciaEsaz { get; set; }
        public string puntoProduttore { get; set; }
        public string ragioneSociale { get; set; }
        public string rapp1 { get; set; }
        public string rapp2 { get; set; }
        public string recorrido { get; set; }
        public string saldo { get; set; }
        public string scala { get; set; }
        public string scontoPotF3 { get; set; }
        public string situazForn { get; set; }
        public string somPot { get; set; }
        public string sottostatoPresa { get; set; }
        public string statoCliente { get; set; }
        public string statoPresa { get; set; }
        public string tariffario { get; set; }
        public string telefono { get; set; }
        public string tensFor { get; set; }
        public string tensione { get; set; }
        public string tipoCliente { get; set; }
        public string tipoMisuratore { get; set; }
        public string tipoOpzione { get; set; }
        public string tipoRiprogr { get; set; }
        public string tipoTariffa { get; set; }
        public string valorePerc { get; set; }
        public string via { get; set; }
        public string viaEsaz { get; set; }
        public string codSocieta { get; set; }
        public string gruppo { get; set; }
        //public string tipoLavoro { get; set; }        
        public string lotto { get; set; }
        public string idOrdineLavoro { get; set; }
        public string centroOperativo { get; set; }

        //Letture
        public List<AcquisizioneLavoroLetturaDTO> listaLetture { get; set; }
        //public string anomalyCode { get; set; }
        //public string anomalyReasoncode { get; set; }
        //public string enAttImmF1 { get; set; }
        //public string enAttImmF2 { get; set; }
        //public string enAttImmF3 { get; set; }
        //public string enAttImmTot { get; set; }
        //public string enAttPrelF1 { get; set; }
        //public string enAttPrelF2 { get; set; }
        //public string enAttPrelF3 { get; set; }
        //public string enAttPrelTot { get; set; }
        //public string enReatF1 { get; set; }
        //public string enReatF2 { get; set; }
        //public string enReatF3 { get; set; }
        //public string enReatQ1Tot { get; set; }
        //public string enReatQ2F1 { get; set; }
        //public string enReatQ2F2 { get; set; }
        //public string enReatQ2F3 { get; set; }
        //public string enReatQ2Tot { get; set; }
        //public string enReatQ3F1 { get; set; }
        //public string enReatQ3F2 { get; set; }
        //public string enReatQ3F3 { get; set; }
        //public string enReatQ3Tot { get; set; }
        //public string enReatQ4Tot { get; set; }
        //public string manufacturer { get; set; }
        //public string matrLetturista { get; set; }
        //public string model { get; set; }
        //public string note { get; set; }
        //public string piccoEnReatF1 { get; set; }
        //public string piccoEnReatF2 { get; set; }
        //public string piccoEnReatF3 { get; set; }
        //public string podId { get; set; }
        //public string potAttImmF1 { get; set; }
        //public string potAttImmF2 { get; set; }
        //public string potAttImmF3 { get; set; }
        //public string potAttPrelF1 { get; set; }
        //public string potAttPrelF2 { get; set; }
        //public string potAtt_prelF3 { get; set; }
        //public string readingdateContatore { get; set; }
        //public string readingdateSistema { get; set; }
        //public string serialNumber { get; set; }
        //public string sourceCode { get; set; }
        //public string sourceDetail { get; set; }
        //public string sourceType { get; set; }
        //public string codiceMisuratore { get; set; }
        // fim Letture       
      

    }
}
