using Pangea.Entidades.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pangea.Entidades.DTO
{
    public class ClienteModMedidor 
    {
        public string CODICE_ZONA { get; set; }
        public string CFT { get; set; }
        public string CODICE_PRESA { get; set; }
        public string ENELTEL { get; set; }
        public string FLAG_TG { get; set; }
        public string CODICE_GRUPPO { get; set; }
        public string TARIFFARIO { get; set; }
        public string RAPP_1 { get; set; }
        public string RAPP_2 { get; set; }
        public string STATO_PRESA { get; set; }
        public string SOTTOSTATO_PRESA { get; set; }
        public string CODICE_MIS { get; set; }
        public string MATRICOLA_MIS { get; set; }
        public string NOMINATIVO { get; set; }
        public string PREFISSO { get; set; }
        public string VIA { get; set; }
        public string NUM_CIV { get; set; }
        public string CD_CL_MERCEOLOGICA { get; set; }
        public int POT_DISP { get; set; }
        public int SOM_POT { get; set; }
        public int COST_E { get; set; }
        public int COST_P { get; set; }
        public string DT_CONTRATTO { get; set; }
        public string DT_ALLACCIAMENTO { get; set; }
        public string FLAG_MIS_POT { get; set; }
        public int TENSIONE { get; set; }
        public string TENS_FOR { get; set; }
        public string FONDO_SCALA { get; set; }
        public string MATR_1_TA { get; set; }
        public string MATR_2_TA { get; set; }
        public string MATR_3_TA { get; set; }
        public string MATR_4_TA { get; set; }
        public string POD { get; set; }
        public string SCALA { get; set; }
        public string PIANO { get; set; }
        public string INTERNO { get; set; }
        public string CAP { get; set; }
        public string LOCALITA { get; set; }
        public string NUM_TEL1 { get; set; }
        public string NOTE_ACCESSO { get; set; }
        public string CODICE_FISCALE { get; set; }
        public string PARTITA_IVA { get; set; }
        public string COD_U { get; set; }
        public string CIFRE_ATT { get; set; }
        public string DATA_SCADENZA_STR { get; set; }
        public int POTENZA_FRANCHIGIA { get; set; }
        public string SITUAZ_FORN { get; set; }
        public int POT_IMPEGNATA { get; set; }
        public string COD_CONTRIBUTO { get; set; }
        public string COGNOME { get; set; }
        public string NOME { get; set; }
        public string RAGIONE_SOCIALE { get; set; }
        public string DETERMINAZ_CONTI_CONTRATTI { get; set; }
        public string COD_ESAZIONE { get; set; }
        public string CAP_ESAZ { get; set; }
        public string COMUNE_ESAZ { get; set; }
        public string VIA_ESAZ { get; set; }
        public string COMPONENTE_AUC { get; set; }
        public string ENERGIA_AD_F3_ASS { get; set; }
        public string ENERGIA_AD_F3_REL { get; set; }
        public string CIFRE_POTENZA { get; set; }
        public string ENER_ANNUA_COTT { get; set; }
        public string CIFRE_REATTIVA { get; set; }
        public string SCONTO_POT_F3 { get; set; }
        public int POT_AGG_DETRAZ_F3 { get; set; }
        public int POT_AGG_DETRAZ_F3_2 { get; set; }
        public string PERC_MAGGIORAZIONE { get; set; }
        public int POT_CONTR_COTTIMO { get; set; }
        public string DT_FIRMA_CONTR_COMMITT_STR { get; set; }
        public string DT_FIRMA_CONTR_CONTRAE_STR { get; set; }
        public string ID_TIPO_FORNIT { get; set; }
        public string ORE_UTILIZZO { get; set; }
        public string COD_MISURATORE_POT { get; set; }
        public string COD_MISURATORE_REA { get; set; }
        public string COD_INSERZIONE_POTENZA { get; set; }
        public string MATR_MISURATORE_POT { get; set; }
        public string MATR_MISURATORE_REA { get; set; }
        public string FREQUENZA_LETTURA { get; set; }
        public string ID_FASE { get; set; }
        public int TIPO_RIPROGR { get; set; }
        public string NON_DISALIMENTABILE { get; set; }
        public string GESTORE_RETE { get; set; }
        public string TIPO_OPZIONE { get; set; }
        public string FLAG_SWITCH_CESSATO { get; set; }
        public string PROVINCIA { get; set; }
        public string PROVINCIA_ESAZ { get; set; }
        public string LETTURA_ATT_F1 { get; set; }
        public string LETTURA_ATT_F2 { get; set; }
        public string LETTURA_ATT_F3 { get; set; }
        public string LETTURA_ATT_F4 { get; set; }
        public string LETTURA_REA_F1 { get; set; }
        public string LETTURA_REA_F2 { get; set; }
        public string LETTURA_REA_F3 { get; set; }
        public string LETTURA_REA_F4 { get; set; }
        public string LETTURA_POT_F1 { get; set; }
        public string LETTURA_POT_F2 { get; set; }
        public string LETTURA_POT_F3 { get; set; }
        public string LETTURA_POT_F4 { get; set; }
        public string FLAG_MANDATO_CONNESSIONE { get; set; }
        public string ID_DISPACC { get; set; }
        public string NAZIONE_ESAZ { get; set; }
        public string DATA_DECORRENZA_MIS { get; set; }
        public string DATA_EFFICACIA { get; set; }
        public string ENELTEL_PRECEDENTE { get; set; }
        public string PUNTO_PRODUTTORE { get; set; }
        public int POTENZA_PRODUZIONE { get; set; }
        public string DATA_CESSAZIONE { get; set; }
        public int SALDO { get; set; }
        public string TIPO_TARIFFA { get; set; }
        public string TIPO_MISURATORE { get; set; }
        public int STATO_CLIENTE { get; set; }
        public string TIPO_CLIENTE { get; set; }
        public int CONST_ENRG_ATTIVA_HR_F1 { get; set; }
        public int CONST_ENRG_ATTIVA_HP_F2 { get; set; }
        public int CONST_ENRG_ATTIVA_FR_F3 { get; set; }
        public int CONST_ENRG_UFER_HP_REATTIVA_F1 { get; set; }
        public int CONST_ENRG_DNCR_HP_REATTIVA_F2 { get; set; }
        public int CONST_ENRG_UFER_FP_REATTIVA_F3 { get; set; }
        public int CONST_ENRG_DNCR_REATTIVA_FP_F4 { get; set; }
        public int CONST_ENRG_UFER_REATTIVA_HR_F5 { get; set; }
        public int CONST_ENRG_DNCR_REATTIVA_HR_F6 { get; set; }
        public int CONST_ENRG_PTNZ_ATTIVA_HR_F1 { get; set; }
        public int CONST_ENRG_PTNZ_ATTIVA_HP_F2 { get; set; }
        public int CONST_ENRG_PTNZ_ATTIVA_FP_F3 { get; set; }
        public string DATA_FATTURAZIONE_FISSA { get; set; }
        public string DATA_INIZIO_PROVA { get; set; }
        public string DATA_FINE_PROVA { get; set; }
        public int INICIAL { get; set; }
        public string CLASSE { get; set; }
        public string CLASSE_E_SUB { get; set; }
        public int VALORE_PERC { get; set; }
        public string podId { get; set; }
        public string manufacturer { get; set; }
        public string model { get; set; }
        public string serialNumber { get; set; }
        public string sourcetype { get; set; }
        public string readingDatedelSistema { get; set; }
        public string readingDatedelContatore { get; set; }
        public string Note { get; set; }
        public string matricolaletturista { get; set; }
        public string EnergiaAttivaPrelevata { get; set; }
        public string EnergiaReattivaQ1 { get; set; }
        public string EnergiaReattivaQ4 { get; set; }
        public string EnergiaAttivaImmessa { get; set; }
        public string EnergiaReattivaQ2 { get; set; }
        public string EnergiaReattivaQ3 { get; set; }
        public string CIFRE_DECIMALI_ATTIVA { get; set; }
        public string CIFRE_DECIMALI_REATTIVA { get; set; }
        public string CIFRE_DECIMALI_POTENZA { get; set; }
        public string LATITUDINE { get; set; }
        public string LONGITUDINE { get; set; }
        public string FLAG_MISURATORE_INTERNO { get; set; }
        public string CLIENTE_SPECIALE { get; set; }
        public string INTERSECCION { get; set; }
        public string TELEFONO { get; set; }
        public string CODIGO_NRO_CONFIG { get; set; }
        public string PRECINTO_T1 { get; set; }
        public string PRECINTO_T2T3_N1 { get; set; }
        public string PRECINTO_T2T3_N2 { get; set; }
        public string PRECINTO_T2T3_N3 { get; set; }
        public string PRECINTO_T2T3_N4 { get; set; }
        public string CODIGO_PARTIDO { get; set; }
        public int anomalyCode { get; set; }
        public string anomalyReasonCode { get; set; }
        public string RECORRIDO { get; set; }
        public string ADVLECTURISTA { get; set; } 

        
    }
}
