using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Solus.Modelo.SalesForce
{
    public class Synergia
    {
        public string identificador_conta { get; set; }
        public string nombre { get; set; }
        public string tipo_identidade { get; set; }
        public string documento_cliente { get; set; }
        public string mail { get; set; }
        public string telefone1 { get; set; }
        public string telefone2 { get; set; }
        public string telefone3 { get; set; }
        public string moneda { get; set; }
        public string tipo_registro { get; set; }
        public string fecha_nasc { get; set; }
        public string cuenta_principal { get; set; }
        public string apellido_materno { get; set; }
        public string direccion { get; set; }
        public string ejecutivo { get; set; }
        public string giro { get; set; }
        public string clase_servicio { get; set; }
        public string id_empresa { get; set; }
        public string razao_social { get; set; }
        public string identificador_contacto { get; set; }
        public string nombre_contacto { get; set; }
        public string apellido { get; set; }
        public string saludo { get; set; }
        public string identificador_conta_contato { get; set; }
        public string estado_civil_contato { get; set; }
        public string genero_contato { get; set; }
        public string tipo_identidade_contato { get; set; }
        public string numero_identidade_contato { get; set; }
        public string fase_ciclo_vida { get; set; }
        public string estrato { get; set; }
        public string nivel_educacion { get; set; }
        public string permite_uso_datos_personales { get; set; }
        public string no_llamar { get; set; }
        public string no_recibir_correo_eletronico { get; set; }
        public string profesion { get; set; }
        public string ocupacion { get; set; }
        public string fecha_nascimento { get; set; }
        public string canal_preferente_contato { get; set; }
        public string correo_eletronico_secundario { get; set; }
        public string telefono1_contato { get; set; }
        public string telefono2_contato { get; set; }
        public string moneda_contato { get; set; }
        public string apellido_materno_contato { get; set; }
        public string tipo_acreditacion { get; set; }
        public string direccion_contato { get; set; }
        public string nombre_usuario_twitter { get; set; }
        public string recuento_seguidores_twitter { get; set; }
        public string influencia { get; set; }
        public string tipo_influencia { get; set; }
        public string biografia_twitter { get; set; }
        public string id_usuario_twitter { get; set; }
        public string nombre_usuario_facebook { get; set; }
        public string id_usuario_facebook { get; set; }
        public string id_empresa_contato { get; set; }
        public string identificador_pod { get; set; }
        public string numero_pod { get; set; }
        public string moneda_pod { get; set; }
        public string digito_verificador_pod { get; set; }
        public string direccion_pod { get; set; }
        public string estado_pod { get; set; }
        public string pais { get; set; }
        public string comuna { get; set; }
        public string tipo_segmento { get; set; }
        public string medida_disciplina { get; set; }
        public string id_empresa_pod { get; set; }
        public string electrodependiente { get; set; }
        public string tarifa { get; set; }
        public string tipo_agrupacion { get; set; }
        public string full_electric { get; set; }
        public string nombre_boleta { get; set; }
        public string ruta { get; set; }
        public string direccion_reparto { get; set; }
        public string comuna_reparto { get; set; }
        public string propiedad_medidor { get; set; }
        public string modelo_medidor { get; set; }
        public string marca_medidor { get; set; }
        public string numero_medidor { get; set; }
        public string num_transformador { get; set; }
        public string tipo_transformador { get; set; }
        public string tipo_conexion { get; set; }
        public string estrato_socioeconomico { get; set; }
        public string subestacion_electrica_conexion { get; set; }
        public string tipo_medida { get; set; }
        public string num_alimentador { get; set; }
        public string tipo_lectura { get; set; }
        public string bloque { get; set; }
        public string horario_racionamiento { get; set; }
        public string estado_conexao { get; set; }
        public string fecha_corte { get; set; }
        public string codigo_pcr { get; set; }
        public string sed { get; set; }
        public string set_cliente { get; set; }
        public string llave { get; set; }
        public string potencia_capacidad_instalada { get; set; }
        public string cliente_singular { get; set; }
        public string clase_servicio_pod { get; set; }
        public string subclase_servicio { get; set; }
        public string ruta_lectura { get; set; }
        public string tipo_facturacion { get; set; }
        public string mercado { get; set; }
        public string carga_aforada { get; set; }
        public string ano_fabricacion { get; set; }
        public string centro_poblado { get; set; }
        public string identificador_asset { get; set; }
        public string nombre_del_activo { get; set; }
        public string identificador_conta_asset { get; set; }
        public string identificador_contato_asset { get; set; }
        public string suministro { get; set; }
        public string descripcion { get; set; }
        public string producto { get; set; }
        public string estado { get; set; }
        public string contrato { get; set; }
        public string moneda_address { get; set; }
        public string esquina_via_sec { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string cep { get; set; }
        public string identificador_address { get; set; }
        public string identificador_street_address { get; set; }
        public string barrio { get; set; }
        public string tipo_numeracion { get; set; }
        public string direccion_concatenada { get; set; }
        public string bloque_direccion { get; set; }
        public string coord_x { get; set; }
        public string coord_y { get; set; }
        public string nombre_agrupacion { get; set; }
        public string tipo_agrupacion_address { get; set; }
        public string tipo_interior { get; set; }
        public string direccion_larga { get; set; }
        public string lote_manzana { get; set; }
        public string tipo_sector { get; set; }
        public string identificador_street { get; set; }
        public string identificador_conta_billing { get; set; }
        public string tipo { get; set; }
        public string identificador_address_billing { get; set; }
        public string apellido_paterno { get; set; }
    }
}
