//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesforceExtractor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalesforceExtractor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///id_sales_conta identificador_conta,
        ///c.nombre,
        ///c.tipo_ident,
        ///nvl(trim(c.rut),&apos;&apos;) || nvl(trim(c.dv_rut),&apos;&apos;) documento_cliente,
        ///case when gc.email not like &apos;%@%&apos; or gc.email is null then &apos;&apos; else replace(replace(replace(trim(gc.email),chr(13),&apos;&apos;),chr(10), &apos;&apos;),&apos;|&apos;,&apos;&apos;)  end as mail,
        ///trim(c.telefono) as telefone1,
        ///trim(gc.tel_contato) as telefono2,
        ///&apos;&apos; as telefono3,
        ///&apos;BRL&apos; moneda,
        ///nvl(desc_tabla(&apos;TIPIDE&apos;,(case 
        ///    when c.tipo_ident = &apos;002&apos; then &apos;002&apos;
        ///	when c.tipo_ident = &apos;003&apos; then &apos;005&apos;
        ///	else
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuerySalesForceA {
            get {
                return ResourceManager.GetString("QuerySalesForceA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    &apos;&apos; AS identificador_conta,--1
        ///c.nombre,--2
        ///
        ///case when nvl(d.tipo_documento,&apos;&apos;) = &apos;&apos;  then trim(c.tipo_ident)
        ///else trim(d.tipo_documento) end tipo_identidade,--3
        ///
        ///case when nvl(d.tipo_documento,&apos;&apos;) = &apos;&apos;  THEN
        ///       nvl(trim(c.rut),&apos;&apos;) || nvl(trim(c.dv_rut),&apos;&apos;)
        ///else
        ///     nvl(trim(d.numero_doc),&apos;&apos;) || nvl(trim(d.dv_documento),&apos;&apos;)
        ///end documento_cliente,  --4
        ///
        ///case when c.mail not like &apos;%@%&apos; or c.mail is null then &apos;&apos;  else replace(replace(c.mail,chr(13),&apos;&apos;),chr(10), &apos;&apos;)  end as mail, -- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuerySalesForceB {
            get {
                return ResourceManager.GetString("QuerySalesForceB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct numero_cliente, desc_tabla(&apos;MODIF&apos;, codigo_modif, &apos;0000&apos;) descricao, codigo_modif, &apos;B&apos; grupo from modif
        ///where codigo_modif 
        ///in(2,3,4,5,7,8,20,22,26,35,36,53,46,48,54,55,56,57,58,59,60,64,87,147,202,205,308,471)
        ///and proced != &apos;DELTAREVERSO&apos;
        ///and date(fecha_modif) = today - parametroDias
        ///and numero_cliente = 890205
        ///union
        ///select distinct numero_cliente, &apos;TROCA DE MEDIDOR&apos; descricao, &apos;M&apos; codigo_modif,&apos;B&apos; grupo from cli_med_processo
        ///where data_atualizacao = today - parametroDias
        ///--and num [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuerySalesForceModif {
            get {
                return ResourceManager.GetString("QuerySalesForceModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT count(numero_cliente), descricao, grupo
        ///FROM temp_clientes_modif
        ///GROUP BY descricao,grupo.
        /// </summary>
        internal static string QuerySalesForceRelModif {
            get {
                return ResourceManager.GetString("QuerySalesForceRelModif", resourceCulture);
            }
        }
    }
}
