//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pangea.Swat.UI.WsSolucoes {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Corte", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Corte : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string documento1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dvDoc1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoFaturamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoFornecimentoField;
        
        private int loteFaturamentoField;
        
        private string CodigoErrorField;
        
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VitalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Guion {
            get {
                return this.GuionField;
            }
            set {
                if ((object.ReferenceEquals(this.GuionField, value) != true)) {
                    this.GuionField = value;
                    this.RaisePropertyChanged("Guion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((object.ReferenceEquals(this.MontoField, value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Hora {
            get {
                return this.HoraField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraField, value) != true)) {
                    this.HoraField = value;
                    this.RaisePropertyChanged("Hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Motivo {
            get {
                return this.MotivoField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoField, value) != true)) {
                    this.MotivoField = value;
                    this.RaisePropertyChanged("Motivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string documento1 {
            get {
                return this.documento1Field;
            }
            set {
                if ((object.ReferenceEquals(this.documento1Field, value) != true)) {
                    this.documento1Field = value;
                    this.RaisePropertyChanged("documento1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string dvDoc1 {
            get {
                return this.dvDoc1Field;
            }
            set {
                if ((object.ReferenceEquals(this.dvDoc1Field, value) != true)) {
                    this.dvDoc1Field = value;
                    this.RaisePropertyChanged("dvDoc1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string EstadoCliente {
            get {
                return this.EstadoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoClienteField, value) != true)) {
                    this.EstadoClienteField = value;
                    this.RaisePropertyChanged("EstadoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string EstadoFaturamento {
            get {
                return this.EstadoFaturamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoFaturamentoField, value) != true)) {
                    this.EstadoFaturamentoField = value;
                    this.RaisePropertyChanged("EstadoFaturamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string estadoFornecimento {
            get {
                return this.estadoFornecimentoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoFornecimentoField, value) != true)) {
                    this.estadoFornecimentoField = value;
                    this.RaisePropertyChanged("estadoFornecimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int loteFaturamento {
            get {
                return this.loteFaturamentoField;
            }
            set {
                if ((this.loteFaturamentoField.Equals(value) != true)) {
                    this.loteFaturamentoField = value;
                    this.RaisePropertyChanged("loteFaturamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public string CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoErrorField, value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Vital {
            get {
                return this.VitalField;
            }
            set {
                if ((object.ReferenceEquals(this.VitalField, value) != true)) {
                    this.VitalField = value;
                    this.RaisePropertyChanged("Vital");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsSolucoes.SalesForceEmergenciaSoap")]
    public interface SalesForceEmergenciaSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento empresa no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCorteEnergia2", ReplyAction="*")]
        Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2Response GetCorteEnergia2(Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCorteEnergia2", ReplyAction="*")]
        System.Threading.Tasks.Task<Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2Response> GetCorteEnergia2Async(Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCorteEnergia2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCorteEnergia2", Namespace="http://tempuri.org/", Order=0)]
        public Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2RequestBody Body;
        
        public GetCorteEnergia2Request() {
        }
        
        public GetCorteEnergia2Request(Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCorteEnergia2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public string numerocliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string dv_numeroCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string empresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string tipo_consulta;
        
        public GetCorteEnergia2RequestBody() {
        }
        
        public GetCorteEnergia2RequestBody(string numerocliente, string dv_numeroCliente, string empresa, string tipo_consulta) {
            this.numerocliente = numerocliente;
            this.dv_numeroCliente = dv_numeroCliente;
            this.empresa = empresa;
            this.tipo_consulta = tipo_consulta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCorteEnergia2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCorteEnergia2Response", Namespace="http://tempuri.org/", Order=0)]
        public Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2ResponseBody Body;
        
        public GetCorteEnergia2Response() {
        }
        
        public GetCorteEnergia2Response(Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCorteEnergia2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Pangea.Swat.UI.WsSolucoes.Corte GetCorteEnergia2Result;
        
        public GetCorteEnergia2ResponseBody() {
        }
        
        public GetCorteEnergia2ResponseBody(Pangea.Swat.UI.WsSolucoes.Corte GetCorteEnergia2Result) {
            this.GetCorteEnergia2Result = GetCorteEnergia2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SalesForceEmergenciaSoapChannel : Pangea.Swat.UI.WsSolucoes.SalesForceEmergenciaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesForceEmergenciaSoapClient : System.ServiceModel.ClientBase<Pangea.Swat.UI.WsSolucoes.SalesForceEmergenciaSoap>, Pangea.Swat.UI.WsSolucoes.SalesForceEmergenciaSoap {
        
        public SalesForceEmergenciaSoapClient() {
        }
        
        public SalesForceEmergenciaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesForceEmergenciaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesForceEmergenciaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesForceEmergenciaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2Response Pangea.Swat.UI.WsSolucoes.SalesForceEmergenciaSoap.GetCorteEnergia2(Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2Request request) {
            return base.Channel.GetCorteEnergia2(request);
        }
        
        public Pangea.Swat.UI.WsSolucoes.Corte GetCorteEnergia2(string numerocliente, string dv_numeroCliente, string empresa, string tipo_consulta) {
            Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2Request inValue = new Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2Request();
            inValue.Body = new Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2RequestBody();
            inValue.Body.numerocliente = numerocliente;
            inValue.Body.dv_numeroCliente = dv_numeroCliente;
            inValue.Body.empresa = empresa;
            inValue.Body.tipo_consulta = tipo_consulta;
            Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2Response retVal = ((Pangea.Swat.UI.WsSolucoes.SalesForceEmergenciaSoap)(this)).GetCorteEnergia2(inValue);
            return retVal.Body.GetCorteEnergia2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2Response> Pangea.Swat.UI.WsSolucoes.SalesForceEmergenciaSoap.GetCorteEnergia2Async(Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2Request request) {
            return base.Channel.GetCorteEnergia2Async(request);
        }
        
        public System.Threading.Tasks.Task<Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2Response> GetCorteEnergia2Async(string numerocliente, string dv_numeroCliente, string empresa, string tipo_consulta) {
            Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2Request inValue = new Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2Request();
            inValue.Body = new Pangea.Swat.UI.WsSolucoes.GetCorteEnergia2RequestBody();
            inValue.Body.numerocliente = numerocliente;
            inValue.Body.dv_numeroCliente = dv_numeroCliente;
            inValue.Body.empresa = empresa;
            inValue.Body.tipo_consulta = tipo_consulta;
            return ((Pangea.Swat.UI.WsSolucoes.SalesForceEmergenciaSoap)(this)).GetCorteEnergia2Async(inValue);
        }
    }
}
